### PR TITLE
#37 SSR doesn't work for i18n

### PR DESCRIPTION
**Pull request by StanislavSt**
Remove the old custom implementation of i18n and use [next-i18next](https://github.com/isaachinman/next-i18next) instead.

Closes https://github.com/daritelska-platforma/frontend/issues/37
## Screenshots:

| Before              | After              |
| ------------------- | ------------------ |
| srr-before | srr-now

**New dependencies**:
- `next-i18next` : v8.0.2

### CODE REVIEW

**Comment by kachar** [comment]
The build problem seems to be reported at https://github.com/isaachinman/next-i18next/issues/995

**Comment by StanislavSt** [comment]
Will convert this to a draft for now until there are more news.

**Comment by kachar** [comment]
I guess we can avoid the issue if we import the types for @types/hoist-non-react-statics package temporary 

Do you think it's worth it ?

**Comment by StanislavSt** [comment]
If we do that, another set if issues will follow :(
image

**Review by kachar — APPROVED** [review]
@StanislavSt Awesome integration! Smooth as jazz :saxophone:

**Pull request merged**
